version: "3.8"
services:
  one-system-db:
    container_name: lyceum-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/lyceum-postgres
    ports:
      - "5432:5432"
    networks:
      - private
      - public
    restart: unless-stopped

  one-system-dms:
    container_name: lyceum-pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/lyceum-pg-admin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - private
      - public
    restart: unless-stopped

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  postgres:
  pgadmin:
    driver: local
